- README.md
- lib/postgrex/types.ex
- test/query_test.exs
- test/test_helper.exs
This PR adds basic support for Postgres' built-in range type (binary format). Currently it handles 5 of the 6 range types: int4range, int8range, daterange, tsrange, and tstzrange. The one that's missing is numrange for Numerics.
Each range type expects and returns a tuple with elements that follow the existing data representation for int, date, and timestamp (e.g., `{1,3}` and `{{2014,1,1},{2014,12,31}}`). More structured representations would best be handled downstream with custom encoder/decoders, like Ecto does with Ecto.Date and Ecto.DateTime.
For open-ended ranges, I went with the existing `:"-inf"` and `:inf` style over `nil` values. Using `nil` would be closer to the Postgres query syntax, but `inf` makes the actual behavior more explicit.
One last thing to note is that the values …
> Add support for Postgres range types

- README.md
Nice and easy :smile:, just changed `.png` to `.svg` in the link to the badge.
> Make the Travis CI badge an SVG image

- lib/postgrex/types.ex
Support citext http://www.postgresql.org/docs/9.4/static/citext.html
citext is a commonly installed extension for Postgres and while it appears to work without explicit inclusion, the array variant `citext[]` does not (casts to binary instead of list).  This pull request remedies this.  I did not add a test because it would require the installation of the citext extension.  Open to any thoughts or feedback, have tested in my app with postgres versions 9.1-9.4.
Thanks,
Troy
> add support for citext (case insensitive text extension)

- lib/postgrex/extensions/binary.ex
added citextsend to @senders to fix.
The encoder was already there, just no entry in @senders
> citext[] type causes 'no extension found for oid' error

- lib/postgrex/utils.ex
got an error parsing "9.4beta2", see #53 
This pull request uses a regex and a case, the regex may be hard to read for some but overall this pr also lowers the LOC ;)  On http://www.postgresql.org/support/versioning they do not mention if a minor version is required, but in the regex I made it optional.
Thanks
> use regex to parse postgres version numbers

- lib/postgrex/extensions/binary.ex
- test/query_test.exs
- test/test_helper.exs
Support for Enumerated Types http://www.postgresql.org/docs/current/static/datatype-enum.html
All seems to work well treating them just like binaries
> add support for pg enum type

- CHANGELOG.md
- README.md
- lib/postgrex/binary_utils.ex
- lib/postgrex/extensions/binary.ex
- lib/postgrex/messages.ex
- test/query_test.exs
Fixes #63
I noticed that there are a few places where oid is treated as int32 not as uint32. I can fix that in a separate PR.
> Support oid and all its aliases

- lib/postgrex/extensions/binary.ex
- test/query_test.exs
Referencing this [PR](https://github.com/ericmj/postgrex/pull/66) and [elixir-lang/ecto#547](https://github.com/elixir-lang/ecto/issues/547) issue.
We've found out that the problem was related with the float's padding, but we're not sure it is the proper fix. What do you think?
> Fix numeric encoding for fractional numbers with less digits than numeric_base.

- lib/postgrex/connection.ex
Both those function basically replicated the behaviour of their non-bang counterparts.
I'm not sure this was an intended behaviour, and if it was I can only imagine it was for performance (I may be completely wrong :smiley:). Not building on top of the non-bang version duplicates a lot of code (almost all code in the functions) and is therefore slightly hard to read and more error prone.
This commit builds those functions on top of their non-bang counterparts. Let me know what you think!
> Refactor Connection.query!/4 and Connection.unlisten!/3

- lib/postgrex/connection.ex
Completely skipped `Postgrex.Connection.listen(!)/3` in the last PR (#70). Sorry :|
> Build Connection.listen!/3 on top of Connection.listen/3

- lib/postgrex/connection.ex
Instead of checking if the hostname that we pass to `:gen_tcp.connect/3` is a binary and converting it to a charlist if it is (`String.to_char_list/1`), we can call `to_char_list/1` which converts anything to a charlist according to the `List.Chars` protocol.
Avoiding `to_char_list/1` may have been intentional though; if this is the case, feel free to close this PR (and maybe explain to me the reason behind this choice so that I can learn something myself :)).
> Use `to_char_list/1` when possible

- lib/postgrex/extensions/binary.ex
- test/custom_extensions_test.exs
- test/schema_test.exs
- test/test_helper.exs
I've tried to remove schema prefix for TypeInfo fields in Types.build_types/1. But it looks like a strange hack and could lead to side-effects besides.
And in any case it won't be enough.
Types are preloaded with Types.bootstrap_query/2, which also use send matchers in SQL query like 
``` sql
SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
t.typelem, coalesce(r.rngsubtype, 0), ARRAY (
SELECT a.atttypid
FROM pg_attribute AS a
WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
)
FROM pg_type AS t
LEFT JOIN pg_range AS r ON r.rngtypid = t.oid
WHERE
t.typname::text = ANY ((ARRAY[])::text[]) OR
t.typsend::text = ANY ((ARRAY['array_send', 'range_send', 'record_send', 'cidsend', 'xidsend', 'regtypesend', 'regclasssend', …
```
> Improved support of hstore for case when hstore extension is created inside a PG schema

- README.md
- lib/postgrex.ex
- lib/postgrex/connection.ex
- lib/postgrex/protocol.ex
- lib/postgrex/result.ex
- lib/postgrex/type_server.ex
- lib/postgrex/types.ex
- mix.exs
- test/custom_extensions_test.exs
- test/login_test.exs
- test/query_test.exs
- test/schema_test.exs
- test/test_helper.exs
- test/type_server_test.exs
This pull request:
1. caches types on ETS to save memory
2. move processing to clients
3. allow clients to decode manually, with an optional mapper function to avoid traversing the collection multiple times
> Store types in ETS and move processing to clients

- lib/postgrex/protocol.ex
- test/query_test.exs
- test/test_helper.exs
> RhodiumToad: that first sync shouldn't be there
> RhodiumToad: if you need the result of the describe before doing the bind, then use flush, not sync
This changes Postgrex to not send parse/describe/sync but parse/describe/flush.
> Send parse/describe/flush not parse/describe/sync.

- README.md
Just a little update in the "Usage" section in the README.
> Updating README - Changing to v0.9.1 version in the usage section

- lib/postgrex/builtins.ex
ranges for `date` and `datetime` builtins were incorrectly typed as `1..12`
> date types

- lib/postgrex/error_code.ex
- test/error_code_test.exs
I'm using postgrex with some plpgsql functions that raise a custom error. The code to string conversion should fall through to return the code if the code is not in the list of errors.
> Unknown error codes should return rather than fail to match

- lib/postgrex/messages.ex
This addresses #96. While Postgres's documentation on its use of signed vs unsigned integers is nearly non-existent, digging into [its source code](http://doxygen.postgresql.org/fe-misc_8c_source.html#l00272) shows that a uint16 is being used to store the number of parameters (Postgres's `getParamDescriptions` method calls into `pgGetInt` with a size of 2, which uses `uint16`).
I also [found discussions](http://www.postgresql.org/message-id/20120901160523.GD2969@momjian.us) that sometimes they use signed integers and sometimes unsigned.
Because of this uncertainty, I'm uncomfortable changing other clauses of `parse` to use unsigned integers without double checking each one.
I would LOVE to have a test for this change, but I have no clue where to even start on testing this (and it looks …
> Change `len` to uint16 for parsing parameter_desc

- lib/postgrex/protocol.ex
- lib/postgrex/types.ex
On master the TypeInfo struct and the extension options are copied from ETS for every term in every row, which means row x column lookups. As this information is the same for every row it is more efficient to lookup this information once per column, i.e. 1 x column lookups. The gain here is not just in terms of skipping the lookup time but less garbage is created because terms are copied from ETS to the calling process on lookup.
I rewrote the `decode_rows/3` function to be slightly more efficient too.
> Cache extension info when decoding

- lib/postgrex/connection.ex
- lib/postgrex/protocol.ex
- lib/postgrex/result.ex
- lib/postgrex/utils.ex
- test/custom_extensions_test.exs
- test/notification_test.exs
- test/query_test.exs
- test/test_helper.exs
Warning: This PR is missing tests for its new queue functionality.
Currently in Postgrex a query is carried out in the Connection process. This means the client has to copy statement/params to the Connection and the Connection has to copy the result to the client. The result might be large and can take a significant time to decode.
There are two steps in Postgrex to decoding the result. First the tcp stream is decoded into tuple packets based on the postgresql binary protocol and then the tuples are converted into relevant terms based on postgrex extensions. Converting from the tuple packet to a relevant term is the slowest of those two steps.
This PR moves the socket communication from the Connection process to the client process. This means that terms do not need to be copied between …
> Allow decoding result without blocking connection

- lib/postgrex/connection.ex
- lib/postgrex/messages.ex
- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- lib/postgrex/result.ex
- test/query_test.exs
- test/test_helper.exs
Currently queries are parse/described for every query and then connection is blocked while the parameters are encoded. This branch allows the statement to parsed as a separate action. The parsed query can then be used to encode parameters without blocking the connection and executed.
Parsed queries can be reused multiple times to encode parameters and execute. Everytime a parsed query is reused it saves a round trip to postgresql and allows postgresql to cache query plans if it can.
Once parsed queries are no longer needed they can be closed to free resources in postgresql.
As an optimisation a parsed query caches both encode and decode information so that executing a parsed query does not need to do any ETS lookups for most types.
> Allow encoding parameters without blocking connection

- test/query_test.exs
This is a bug fix for tag `v0.10.0`. The bug is fixed on master by coincidence. Could we have a branch for `v0.10` so we can backport fixes without introducing prepare/execute into `v0.10.*`? This PR is not mergable.
This bug was reported in #129  but was hidden by an issue with Ecto (see https://github.com/elixir-lang/ecto/issues/1161).
> Do not shutdown on binding error

- mix.exs
Fixes an error with newer hex:
```
** (Mix) earmark is missing its version requirement, use ">= 0.0.0" if it should match any version
```
> Specify version for ex_doc and earmark deps

- lib/postgrex.ex
- lib/postgrex/connection.ex
- lib/postgrex/notifications.ex
- lib/postgrex/parameters.ex
- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- lib/postgrex/result.ex
- lib/postgrex/utils.ex
- mix.exs
- mix.lock
- test/login_test.exs
- test/query_test.exs
- test/test_helper.exs
- test/transaction_test.exs
This is WIP.
Issues:
There are two optimisations in this change because the `DBConnection` API is not exactly equivalent to the old `Postgrex.Connection`:
* Notifications are sent as soon as they are received and are not accumulated.
* Type information for a query can be looked up without blocking the connection. I am unsure how useful it is as the client will likely be holding on to the connection about to execute.
Will need to do benchmark/profile to check performance does not regress before merging.
I have not added any new features in this PR and would prefer these to come one by one in separate PRs. The features (pooling, transactions, network failure handling, idle timeout) require implementing simple callbacks, documenting options and/or wrapping `DBConnection` calls so are almost …
> Use DBConnection

- lib/postgrex/error.ex
- lib/postgrex/protocol.ex
- lib/postgrex/result.ex
- test/query_test.exs
I don't feel good about retrieving the `connection_id` all over the place, but I couldn't come up with anything nicer. Recommendations?
Also I'm not sure about whether the key should be `connection_id` or `backend_pid`. IMO from the Postgre(s|x) perspective it's clearly the `backend_pid`, only from Ecto's ORM-independent perspective does the `backend_pid` become the `connection_id`.
> Add connection_id to Postgrex.Result and Postgrex.Error. Fixes #137.

- lib/postgrex/messages.ex
- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- lib/postgrex/result.ex
Only traverse and reverse the row once, instead of twice.
> Delay row decoding

- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- test/query_test.exs
Previously when executing a query prepared on another connection, the connection would try to execute, prepare and then execute the query. This took 3 round trips. This change does prepare and execute in 1 round trip when the query was already described. Therefore when we use prepared cached queries in Ecto we only need to do one 2 round trip to postgres per cached query.
Previously when executing a prepared query on a connection with a different query prepared with the same name, the different query would be executed. This change ensures the names and statements match before executing.
> Skip describe when executing described query

- lib/postgrex/connection.ex
- lib/postgrex/protocol.ex
- test/transaction_test.exs
The tests don't actually use savepoints yet, which means savepoint transactions aren't usable in postgrex itself.
> Test savepoint transactions

- lib/postgrex/protocol.ex
- test/query_test.exs
Previously we did not handle the case where a parse error occurs and a `sync` has already been sent. Another `sync` was sent and only one `ready` was received. This left another `ready` packet in the buffer and crashes the next request.
Closes #149.
> Handle parse error when part of handle_execute(_close)

- lib/postgrex/builtins.ex
- lib/postgrex/extensions/point.ex
- lib/postgrex/utils.ex
- test/query_test.exs
This is a rebased version of #126, updated to account for the upstream extension changes.
Thanks to @jbavari for doing the hard work of figuring out how to create the type and all the initial coding on this.
> Add basic support for built-in postgres point type

- lib/postgrex/utils.ex
- test/login_test.exs
This fixes :inet_tcp.getserv/1 receiving a binary which it has no matching available.
If there is a smarter way of doing this, let me know! This is my first piece of code in Elixir. :tada:
> Use PGPORT as an integer.

- lib/postgrex/protocol.ex
- test/query_test.exs
- test/test_helper.exs
If a function called while executing a query raises a notice, rows returned prior to calling that function will be dropped. This change reinjects the previous rows into `execute_recv/5` rather than falling back to `excute_recv/4`.
Test is included. Let me know if you have any questions.
Thanks!
> Fix result set truncation when functions that raise notices are called during query execution

- lib/postgrex.ex
- lib/postgrex/binary_extension.ex
- lib/postgrex/extensions/hstore.ex
- lib/postgrex/extensions/json.ex
- lib/postgrex/extensions/raw.ex
- lib/postgrex/protocol.ex
- lib/postgrex/types.ex
- lib/postgrex/utils.ex
- test/query_test.exs
`:decode_binary` is either `:copy` or `:reference`.
* `:copy` uses `:binary.copy/1` to copy values decoded as binaries.
* `:reference` uses a reference counted binary from the binary streamed from the
socket.
If binaries are being held on to for a substantial period of time, sent to
other process, or inserted into ETS it may prevent garbage collection of a
larger binary. This option copies by default so that extra memory is not
consumed. If binaries are going to be garbage collected soon it will be
more efficient to use a reference binary.
Closes #167.
> Add `:decode_binary` option to copy decoded values

- lib/postgrex.ex
- lib/postgrex/utils.ex
- test/login_test.exs
In addition to the `PGPORT` fallback, now the given port number is also converted from string to integer.
Related: elixir-lang/ecto#544 and #171.
> Convert the port number to integer

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/transaction_test.exs
* Allows `mode: :savepoint` on prepare/execute/close that acts like `ON_ERROR_ROLLBACK` in psql. Using this means that transaction won't fail if an error is returned. If request is successful then does not add roundtrips to the database. On error adds an extra roundtrip.
* Track postgresql backend status and rollback to savepoint if failed after savepoint transaction
See https://github.com/elixir-lang/ecto/issues/1459
> Prepare fix for Ecto sandbox inconsistencies

- lib/postgrex/protocol.ex
- test/query_test.exs
Closes #185.
It appears there is a built in limit to how much can be received and this is constant throughout multiple OS. People report 16MB, 32MB and 64MB as time progresses.
http://erlang.org/pipermail/erlang-questions/2006-September/022909.html
https://github.com/rabbitmq/rabbitmq-erlang-client/blob/591ddb8abce27e9737de3d373b7da40cc2c88453/src/amqp_network_connection.erl#L239
https://github.com/exxeleron/qErlang/blob/fbca1ba1f1234c3f9aef1f9a13d0234b70e19709/src/qErlang.erl#L137
I am awaiting a reply to check 64MB is a hard limit or how it is configured.
> Receive packets greater than 64MB

- lib/postgrex.ex
- lib/postgrex/messages.ex
- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- lib/postgrex/stream.ex
- test/query_test.exs
- test/stream_test.exs
- test/transaction_test.exs
Closes #183 and #202.
This uses a different approach for copying "FROM STDIN" or to the database to #202, one query is done and then items are added a continuous stream. Importantly it adds support for copying to the database using a single query and allows data chunks to contain incomplete rows when using a stream. This requires some more complex code to ensure that streaming and non-streaming versions have identical behaviour and that we support `mode: :savepoint`.
Note that if an error occurs causing the `Enum.into/2,3` to be halted the copy as a whole fails and marks the transaction as failed (unless using `mode: :savepoint`) but does not raise (hide the initial failure).
Some more test are required to check edge cases.
> Add support for COPY TO STDOUT and COPY FROM STDIN

- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- test/alter_test.exs
- test/query_test.exs
- test/stream_test.exs
- test/test_helper.exs
Match cached queries by name and referenced rather than name and statement.
Initial work towards #212. This PR means we should always error if types change.
> Detect stale types when executing prepared queries

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- mix.exs
- mix.lock
* Parse query on backend once (instead of twice) when unnamed
* Savepoint once (instead of twice) when savepointing queries
Requires latest DBConnection!
Closes #219. Closes #218.
> Only sync with backend once when doing query/4

- lib/postgrex/extensions/calendar.ex
- lib/postgrex/extensions/time.ex
- test/calendar_test.exs
- test/query_test.exs
- test/test_helper.exs
Initial work on Calendar types. Closes #192.
/cc @lau
> Add support for Elixir 1.3+ Calendar types

- lib/postgrex.ex
There is no `Postgrex.prepare/2`.
> Include missing name argument

- test/calendar_test.exs
Running the tests locally, I receive this:
1) test decode timestamptz (CalendarTest)
test/calendar_test.exs:82
match (=) failed
code: [[%DateTime{year: 2001, month: 1, day: 1, hour: 0, minute: 0, second: 0, microsecond: {0, 6}, time_zone: "Etc/UTC", utc_offset: 0}]] = query("SELECT timestamp with time zone '2001-01-01 00:00:00'", [])
rhs:  [[%DateTime{calendar: Calendar.ISO, day: 31, hour: 23,
microsecond: {0, 6}, minute: 0, month: 12, second: 0,
std_offset: 0, time_zone: "Etc/UTC", utc_offset: 0, year: 2000,
zone_abbr: "UTC"}]]
stacktrace:
test/calendar_test.exs:83: (test)
This is because the input is being interpreted using my development laptop's time zone (CET) which on January 1st would be on hour ahead of UTC.
Unless Postgrex should set the time zone to UTC upon connection, it seems …
> Specify time zone

- lib/postgrex/types.ex
- test/alter_test.exs
- test/test_helper.exs
Previously would not include old types information when rebootstrapping so could not bootstrap a composite type that included a type that was already bootstrapped.
> Fix rebootstrapping composite types

- lib/postgrex.ex
- lib/postgrex/utils.ex
- test/login_test.exs
I'd like to be able to configure my database name in production via environment variable and this would help. (FWIW I'm an Elixir and Ecto newbie. Happy to make changes if needed.)
> Make postgrex respect env var PGDATABASE like libpq.

- lib/postgrex/error.ex
- test/error_test.exs
- test/stream_test.exs
1. Modified Postgrex error messages to format `SEVERITY PGCODE
(PGCODE_TO_NAME): MESSAGE`
2. Changed regex on `ERROR (PGCODE_TO_NAME)` to match on `(PGCODE_TO_NAME)` in seven `stream_test` test.
tests consistent with changes in 1.
3. Added assertion to `error_test` to regex match 5 numeric digits in
error message consistent with changes in 1.
> PG Code in Error Message - Closes #242

- lib/postgrex.ex
- mix.lock
This PR does two things:
1. Updates ex_doc to 0.14.3, so that we can cross link to DBConnection docs
2. Updates `Postgrex.start_link` to mention `after_connect` as dicussed on: https://github.com/elixir-ecto/db_connection/issues/63#issuecomment-253910368
Rendered:
> Update ex_doc to 0.14.3 and minor docs update for start_link

- lib/postgrex/notifications.ex
I'm trying to listen to the channel with a name containing a hyphen ( "test-test" )
This raises an error
> ** (MatchError) no match of right hand side value: %Postgrex.Error{connection_id: 27143, message: nil, postgres: %{code: :syntax_error, file: "scan.l", line: "1052", message: "syntax error at or near \"-\"", pg_code: "42601", position: "13", routine: "scanner_yyerror", severity: "ERROR"}}
This pull-request fixes this bug
> Use double quotes to listen/unlisten

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- lib/postgrex/stream.ex
- mix.exs
- mix.lock
- test/query_test.exs
- test/stream_test.exs
- test/transaction_test.exs
* No longer require stream to be prepared before use
* Always bind params in a stream's start fun
* Always execute portal in a stream's first next fun
* Report `:num_rows` for each result in a stream
* Identify streams in logs with cursor/copy struct
* Drop support for `:copy_data` parameter
> Use prepare_stream and stream from DBConnection

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- lib/postgrex/type_server.ex
- test/type_server_test.exs
Adds more timeout control, logging on handshake timeout and all waiting connections fail if the bootstrapper fails. This means all connections backoff for a bit so we don't hog the backend. Hopefully it will succeed later. I don't think this will solve the problem but it should provide a better ops experience.
> Fail all waiting connections on bootstrap failure

- .travis.yml
Elixir 1.4 is now released in stable :tada: .
We can test against it instead of the release candidate.
Thanks!
> Test against elixir 1.4.0

- lib/postgrex/types.ex
this restores compatibility with postgres versions prior to 8.4 and with redshift
> replace `unnest` with `generate_series` for compatibility

- README.md
- lib/postgrex/builtins.ex
- lib/postgrex/extensions/tsvector.ex
- lib/postgrex/utils.ex
- test/tsvector_test.exs
Hi,
This PR adds the support for Tsvector extensions.
It's usually used with full text search features that are built in inside postgres.
I wanted to be able to use manually written tsvector and tsquery directory from ecto. However, no extension was available for it, so I implemented one.
If this seems good, I will look to implement tsquery after this PR merges as both are usually used together...
Thanks!
Links to the official postgres doc : https://www.postgresql.org/docs/8.3/static/datatype-textsearch.html
The query tests are the ones from postgresql directly here : https://github.com/postgres/postgres/blob/89fcea1ace40bc025beea2758a80bcd56a319a6f/src/test/regress/sql/tstypes.sql
> Base implementation of Tsvector & Lexeme support

- lib/postgrex.ex
Right not it's only mentioned in the readme.
> Add PgBouncer instructions to regular docs

- lib/postgrex/result.ex
The docs are inconsistent between whether `rows` is a list of tuples or a list of lists.
Changing the moduledocs to use list of lists, rather than list of tuples.
> Postgrex Result module inconsistent docs

- README.md
When the `prepare: :unnamed` weren't used, all the queries timed out. Adding this option seems to have solved the problem, so it's worth adding the information about this case in the docs.
> Add info about pgpool

- lib/postgrex/type_module.ex
`Postgrex.Types.fetch/2` error return is `{:error, TypeInfo.t | nil, module}` but `Postgrex.TypeModule.decode_tuple/5` would try to match to the error tuples `{:error, TypeInfo.t | nil}`, which would cause the following dialyzer error if you used `Postgrex.Types.define/3`:
```erlang
/home/lotte/projects/helm/deps/postgrex/lib/postgrex/type_module.ex:717:
The pattern
{'error', #{'__struct__':='Elixir.Postgrex.TypeInfo', 'type':=_@60}}
can never match the type
{'error', 'nil' | #{'__struct__':='Elixir.Postgrex.TypeInfo', ...}, atom()}
/home/lotte/projects/helm/deps/postgrex/lib/postgrex/type_module.ex:717:
The pattern
{'error', 'nil'}
can never match the type
{'error', 'nil' | #{'__struct__':='Elixir.Postgrex.TypeInfo', ...}, atom()}
```
_note that i edited the dialyzer output for …
> Fix Postgrex.TypeModule.decode_tuple/5 pattern on Postgrex.Types.fetch/2 error return

- lib/postgrex/protocol.ex
- lib/postgrex/types.ex
- test/alter_test.exs
Closes #243. This is WIP.
@mspanc can you check if this branch resolves your issue?
> Reload types on unknown oid during prepare

- lib/postgrex/type_info.ex
- lib/postgrex/types.ex
For example, `CREATE DOMAIN public.validity_range AS tsrange CONSTRAINT …` will create a domain based on `tsrange`, and without the change, the end user must create a custom Postgrex extension to make use of such a type.
In this change, the relevant bootstrap query used by the Type Server to determine base types within a range type is updated to take such domain types into account, so the native Range extension can be used. In addition, the comment within Type Info was updated to reflect the true nature of the underlying value.
> fixes custom range domains not supported natively

- lib/postgrex/types.ex
- test/query_test.exs
- test/test_helper.exs
Array domains do not have `typelem` set in `pg_types` and are not supported out-of-the-box.
For example, this creates an array with a constraint ensuring that it has at least one element.
CREATE DOMAIN public.page_quads AS polygon[]
CONSTRAINT is_populated
CHECK (COALESCE(array_length(VALUE, 1), 0) >= 1);
In this changeset, the bootstrap query used by the Type Server is updated again, so to support this use case without requiring a custom Postgrex extension.
Within the change, I have limited this to PostgreSQL 9.0 and upwards but the version check may actually be unnecessary.
> fixes array domains not supported natively

- lib/postgrex/messages.ex
- lib/postgrex/protocol.ex
- lib/postgrex/stream.ex
- mix.exs
- mix.lock
- test/stream_test.exs
- test/transaction_test.exs
WIP: awaiting DBConnection release
* Adds support for non-stream cursors
* Adds support for advance transaction handling
> Update to latest DBConnection

- lib/postgrex/protocol.ex
- lib/postgrex/stream.ex
- test/query_test.exs
- test/stream_test.exs
- test/transaction_test.exs
Use the same transaction/savepoint messages whether using named queries or otherwise. The control flow is refactored to be more explicit by using with special form.
Closes #323.
> Use simple queries for transactions

- README.md
ref #335 
Doesn't look like travis supports Postgres 10 yet.
> Update readme to specify postgresql 10 support

- test/query_test.exs
- test/type_module_test.exs
This is an awkward situation as we are liberally copying (against documented advice) and in OTP 20 the binary GC is much improved. Therefore we add performance penalty in OTP 20 that shouldn't be required(?). I am unsure if we can deprecate the feature once we are OTP 20+ because I don't know if the leaks could still occur.
> Only test decode binary on OTP <= 19

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- mix.exs
- mix.lock
- test/alter_test.exs
- test/transaction_test.exs
Casting params when preparing a query with known types will prevent errors when types have changed as we can use the encode terms for the params, the new types to decode the result and get a refreshed query struct back.
The only case when we can't handle it gracefully (no error) is if we can't cast the param types from old to new. This will produce a native Postgrex.Error so we no longer have to create a custom error and relies on the database as source. However in that situation a user should be using a new query. This shouldn't occur for Ecto as it should require a schema code reload to get into such a state. Fortunately Ecto will be able to handle the error and reset the query cache in a similar way to when the types change and the query has already been prepared.
Depends on #347.
> Try to cast params if param types change

- .travis.yml
- test/login_test.exs
- test/test_helper.exs
This allows a user to define env to control configuration when testing postgrex. Mariaex and ecto have issues too but didn't consider fixing those yet.
> Use system env during tests

- lib/postgrex/notifications.ex
This fixes dialyzer warnings when using a named process for Postgrex.Notifications.
Eg: the following code:
```elixir
Postgrex.Notifications.start_link(AsyncJobApi.Repo.config() ++ [name: AsyncJobApi.JobQueue.Notifier])
Postgrex.Notifications.listen!(AsyncJobApi.JobQueue.Notifier, "jobs.completed")
```
Produces this warning:
```
[ElixirLS Dialyzer] The call 'Elixir.Postgrex.Notifications':'listen!'('Elixir.AsyncJobApi.JobQueue.Notifier',<<_:112>>) will never return since it differs in the 1st argument from the success typing arguments: (pid(),binary())
```
> Accept GenServer.server() type in Postgrex.Notifications API

- lib/postgrex/utils.ex
Version string for an official postgres repo build looks like this:
10.2 (Ubuntu 10.2-1.pgdg16.04+1)
which the version parser chokes on since it's only expecting something like "10.2".
> fix parsing of version string from latest pgdg repository build

- lib/postgrex/utils.ex
Commit dd6ac4eb claims to backport version parsing from master, but
there are no changes on master to version parsing. This commit improves
resiliency of the version parser.
> Port changes to version parsing

- lib/postgrex/extensions/timestamptz.ex
Fixes:
```
warning: deprecated time unit: :microseconds. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
(elixir) lib/system.ex:898: System.warn/2
(elixir) lib/system.ex:752: System.convert_time_unit/3
(elixir) lib/calendar/datetime.ex:280: DateTime.to_unix/2
(postgrex) lib/postgrex/extensions/timestamptz.ex:33: Postgrex.Extensions.TimestampTZ.encode_elixir/1
(postgrex) lib/postgrex/type_module.ex:714: Postgrex.DefaultTypes.encode_params/3
```
> Fix deprecated time unit warning

- CHANGELOG.md
- lib/postgrex/builtins.ex
- lib/postgrex/extensions/inet.ex
- test/query_test.exs
Pull request to fix an issue mentioned in #383.
> Automatically encode/decode /32 or /128 netmasks

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- lib/postgrex/stream.ex
- mix.exs
- mix.lock
- test/stream_test.exs
This is a series of commits to simplify a bit the implementation:
1. Instead of passing :function metadata, we just track what is important, which is the :prepare flag
2. Do not pass the stream as query, instead pass the query itself and use the stream option
3. Remove the copy structs in favor of tuples
> Reduce the amount of metadata and structs

- README.md
- lib/postgrex/messages.ex
- test/test_helper.exs
We also always infer the postgres version,
rather than depending on an env var to be set.
> Clean up test helper

- lib/postgrex/error.ex
- lib/postgrex/protocol.ex
- lib/postgrex/type_module.ex
- test/custom_extensions_test.exs
- test/query_test.exs
Postgrex.QueryError is better semantically. Another case
was also replaced by DBConnection.ConnectionError.
> Replace ArgumentError/RuntimeError by Postgrex.QueryError

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/transaction_test.exs
Similar to https://github.com/xerions/mariaex/issues/180
Example: script below tries to constantly write and at some point we cause manual failover and expect the system to self-heal:
```elixir
defmodule Aurora.Application do
use Application
def start(_, _) do
opts = [
name: :aurora,
disconnect_on_read_only_transaction_error: true
]
children = [
{Postgrex, opts}
]
Supervisor.start_link(children, strategy: :one_for_one, name: Aurora.Supervisor)
end
end
```
```elixir
Enum.each(1..1000, fn i ->
:timer.sleep(1000)
IO.write(to_string(DateTime.utc_now()))
statement = "INSERT INTO integers (x) VALUES ($1)"
case Postgrex.query(:aurora, statement, [i]) do
{:ok, _result} ->
IO.puts(" (ok)")
{:error, %Postgrex.Error{postgres: %{code: :read_only_sql_transaction}} = exception} ->
IO.puts(" (error)") …
```
> Disconnect on read-only transaction error

- test/query_test.exs
Note we still have `:idle_timeout` option in the codebase for `Postgrex.Notifications` which is unrelated to the DBConnection one: https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/notifications.ex#L13
> DBConnection replaced :idle_timeout with :idle_interval

- README.md
Update readme to specify that `NaiveDateTime` is used for `timestamp` type.
> Update README.md - timestamp type

- lib/postgrex/utils.ex
- test/utils_test.exs
Hi,
When using postgrex with Enterprise DB Postgres, Postgrex isn't able to parse the version since it contains 4 parts. (9.5.5.10 for instance).
This pull request fixes that issue by accepting 4 parts, ignoring the last part.
I couldn't find any documentation regarding that last number, I'm assuming it's a build number.
> Add support for 4-part versions (Enterprise DB)

- mix.exs
We depend on Elixir ~> 1.4 so it's safe
> Use application inference

- lib/postgrex/protocol.ex
When used in FIPS mode, :crypto.hash(:md5, iodata) refuses to do encryption. Authentication using md5 hashed password [is FIPS 140-2 compliant if connection is TLS encrypted](https://docs.oracle.com/cd/E36784_01/html/E54953/fips-notok-1.html). This PR changes use of :crypto.hash/2 function with :erlang.md5/1 as suggested by [erlang documentation](http://erlang.org/doc/apps/crypto/fips.html).
Closes #449
> Replace :crypto.hash/2 with :erlang.md5/1 for authentication

- lib/postgrex/protocol.ex
Fixes #445
* psql (11.1)
* Elixir 1.7.4
* Erlang/OTP 21 [erts-10.2] [source] [64-bit]
* OSX 10.14
To reproduce the issue set `client_min_messages = debug5` in **postgresql.conf**. Postgrex fails:
```
{:ok, pid} = Postgrex.start_link(hostname: "localhost", username: "postgres", password: "postgres", database: "postgres", sync_connect: true)
{:ok, #PID<0.219.0>}
13:07:14.672 [error] GenServer #PID<0.221.0> terminating
** (RuntimeError) connect raised KeyError exception: key :messages not found.The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true if you wish to see all of the details
(stdlib) :maps.get/2
(elixir) lib/map.ex:267: Map.update!/3
(postgrex) lib/postgrex/protocol.ex:2815: …
```
> Fix unexpected messages on handshake

- lib/postgrex/types.ex
The latest version of CockroachDB comes with full support for correlated subqueries which was an issue before. Now the only stoper is one sql fragment where an explicity cast is currently needed.
See: https://github.com/cockroachdb/cockroach/issues/14554
> Add explicit cast for CockroachDB v19.1

- lib/postgrex/extensions/date.ex
- lib/postgrex/utils.ex
- test/calendar_test.exs
Postgrex currently assumes that a date to be encoded is in
the Calendar.ISO calendar (the default). However Elixir
supports different calendar types in the %Date{} struct.
Postgres does not support dates outside the Calendar.ISO
calendar for the Postgres standard date type.
This commit raises the standard DBConnection.EncodeError
error if a date in a different calendar is provided.
> Raise exception if encoding a date that is not in Calendar.ISO

- lib/postgrex/extensions/date.ex
- lib/postgrex/extensions/time.ex
- lib/postgrex/extensions/timestamp.ex
- lib/postgrex/extensions/timestamptz.ex
- lib/postgrex/extensions/timetz.ex
- lib/postgrex/utils.ex
- test/calendar_test.exs
In line with the previous commit, ensures Postgrex only encodes values in the Calendar.ISO calendar.
> Don't encode DateTime, NaiveDateTime or Time unless Calendar.ISO

- lib/postgrex/protocol.ex
In `Postgrex.Protocol` the [command is converted to an atom](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/protocol.ex#L2650) with `String.to_atom/1`.
For Postgres wire-compatible databases like [agensgraph](http://bitnine.net/documentations/quick-guide-1-3.html#overview), commands may be returned that have dynamically generated command names such as `:"graph_write_(insert_vertex_0,_insert_edge_1)"` which could result in blowing up the atom table.
Since Postgres commands always consist of [only A..Z and `0x20`](https://www.postgresql.org/docs/11/static/sql-commands.html) this commit terminates the tag scan whenever a character outside this range is detected which will at least limit the number of potential atoms created without compromising the performance of the …
>  Guard against atom table overflow for non-standard SQL commands

- CHANGELOG.md
- README.md
- lib/postgrex.ex
- lib/postgrex/builtins.ex
- lib/postgrex/error_code.ex
- lib/postgrex/extension.ex
- lib/postgrex/notifications.ex
- lib/postgrex/protocol.ex
- lib/postgrex/result.ex
- lib/postgrex/types.ex
- lib/postgrex/utils.ex
I found that postgrex uses both PostgreSQL and Postgres.
Although Postgres is "widely accepted as nickname or alias" [manual](https://www.postgresql.org/docs/current/history.html), it would be better to stick with the official name here.
... or just change all PostgreSQL to Postgres :)
Also included small typo fix.
> Fix doc: PostgreSQL, not Postgres / typo

- README.md
- lib/postgrex/builtins.ex
- lib/postgrex/extensions/interval.ex
- test/query_test.exs
Implements [#475 ](https://github.com/elixir-ecto/postgrex/issues/475)
Changes:
- `microsecs` field added to `Postgrex.Interval`
- `Postgrex.Extensions.Interval.encode/1` extended
- `Postgrex.Extensions.Interval.decode/1` extended
- tests
- docs update
> Add support for microseconds in Postgrex.Interval

- .travis.yml
Recently I got in a discussion at work if we should use pg 11 or a older version because of no explicit support of `postgrex`. So would be nice to enable PG 11 on travis to guarantee that everything is working.
Include `PGVERSION=11` on `.travis.yml`
> Enable PG 11 on travis

- lib/postgrex.ex
`:ssl.ssl_option/0` is no more and `:ssl.tls_option/0` is the think that should be used instead otherwise [it can be a little bit confusing to the newcomers](https://elixirforum.com/t/how-to-connect-to-postgrex-with-ssl-certificate/26255?u=hauleth).
> Fix `start_options` `:ssl_opts`

- lib/postgrex.ex
Adding more information on where to go for the ssl_options flag. 
Follow up from this forum discussion:
https://elixirforum.com/t/how-to-connect-to-postgrex-with-ssl-certificate/26255
> added link to docs

- lib/postgrex/notifications.ex
- test/notification_test.exs
I finally got around to implementing the notification auto-reconnect that was discussed over in #433. The basic functionality is enabled by adding the `auto_reconnect: true` to the startup opts.
I haven't written any docs yet because I wanted to run the implementation past you before spending time on that. If you're happy with it, I'll update the docs before it's merged.
> Add auto reconnection option for notifications

- lib/postgrex/extension.ex
Example would fail with:
```
** (FunctionClauseError) no function clause matching in Keyword.get/3
The following arguments were given to Keyword.get/3:
:copy
:decode_copy
:copy
Attempted function clauses (showing 1 out of 1):
def get(keywords, key, default) when is_list(keywords) and is_atom(key)
(elixir) lib/keyword.ex:195: Keyword.get/3
lib/postgrex/type_module.ex:878: Postgrex.TypeModule.configure/1
(elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
lib/postgrex/type_module.ex:11: Postgrex.TypeModule.define/3
lib/postgrex/test.ex:51: (file)
```
as `:copy` was passed to the `init/1` callback instead of a keyword list. 
Changed the example to show both passing in a module with and without opts.
> Fix non-working example

- lib/postgrex/notifications.ex
- test/notification_test.exs
When using Ecto, which uses `db_connection`, it's possible to provide dynamic connection configuration for every connection attempt via the `configure` option:
> A function to run before every connect attempt to dynamically configure the options, either a 1-arity fun, `{module, function, args}` with options prepended to `args` or `nil` where only returned options are passed to connect callback (default: `nil`) 
This is useful, for example, because it allows for using [temporary database credentials](https://www.vaultproject.io/docs/secrets/databases/postgresql.html#usage).
The same doesn't work for notifications however, apparently because they don't use the connection pool. This change would allow this.
I've omitted tests so far because I'm not sure this is the right place to fix it. …
> Allow dynamic connection configuration for notifications

- lib/postgrex/extensions/array.ex
libpq supports decoding 0 dimensional arrays, but it encodes them as
empty 1 dimensional arrays. It's therefore unclear how they should be
encoded. Unfortunately, CockroachDB only supports decoding empty 1
dimensional arrays.
Fixes #491
> More compatible empty list encoding

- README.md
Add brief explanation of the implementation and links to Postgres
documentation to help understand operation and debugging.
For example, despite use of terminology such as "prepared statement",
reviewing postgres logs will not reveal `PREPARE` and `EXECUTE`, which
might be confusing.
> Explain the implementation.

- lib/postgrex.ex
> Use :supervisor as child_spec/1 return type

- lib/postgrex/protocol.ex
`bootstrap_recv/4` and in turn `msg_recv/4` expect their first argument
to be a Map (usually a `%Postgrex.Protocol{}` struct), but this
case-clause assigns the entire two element tuple return from
`handle_msg/3` to `s` and then passes it onward.
```
** (FunctionClauseError) no function clause matching in Postgrex.Protocol.msg_recv/4
(postgrex 0.15.8) lib/postgrex/protocol.ex:2837: Postgrex.Protocol.msg_recv({%Postgrex.Protocol{...
should not be a tuple --^^^
```
Although a bug has not yet occurred, a similar problem seems likely due
to same assignment and call-chain in `reload_recv/4` so it has also been
changed.
Closes #498
> WIP: Fix crash following mishandled result.

- lib/postgrex.ex
- lib/postgrex/extension.ex
- lib/postgrex/protocol.ex
- test/login_test.exs
Add a parameter called `target_server_type` inspired by the `targetServerType` parameter in the [Postgres JDBC driver](https://jdbc.postgresql.org/documentation/head/connect.html). This option improves DB fail-overs by ensuring that we are reconnecting to the right instance. It is also mentioned in the AWS [DB fail-over best practices document](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.BestPractices.html#AuroraPostgreSQL.BestPractices.FastFailover).
Based on my testing, from the point of view of the client application, a DB fail-over on AWS Aurora Postgres evolves like this:
1. Let's start with our client app being connected to the primary instance. It is therefore able to do read and write operations on the database.
2. When the fail-over starts, the …
> Ensure that connections are established to the right type of instances

- lib/postgrex/protocol.ex
~I think this may fix~ This fixes the test-failure currently being reported for the gh action `test (13, 1.11.3, 23.2.5)` on master...
> Fix failing test / formatter error (13, 1.11.3, 23.2.5) 

- lib/postgrex/protocol.ex
- test/login_test.exs
Closes https://github.com/elixir-ecto/postgrex/issues/542
If Postgrex tries to connect to more than one database instance and if the connection fails for all of them, one global exception is raised and its message is a concatenation of all the exceptions message (one exception per connection failed). 
This PR doesn't alter the behavior of the library if connection is attempted to only one instance (using either the `hostname` & `port` config options, the UNIX socket option or the `endpoints` option with only one {hostname,port} tuple).
> Improve error handling when using multiple endpoints

- test/login_test.exs
This PR is a minor follow up to https://github.com/elixir-ecto/postgrex/pull/544. I thought it would be better to add those 2 tests to the error handling
> Add tests to the error handling when using multiple endpoints

- .github/workflows/ci.yml
- lib/postgrex/extensions/date.ex
- lib/postgrex/extensions/timestamp.ex
- lib/postgrex/extensions/timestamptz.ex
- test/calendar_test.exs
Supports negative years for the types date, timestamp,
timestampz. A side effect is that the `:calendar` module
is no longer used.
**This implementation support only Elixir 1.11 and 1.12** because
of its use of `NaiveDateTime.to_gregorian_seconds/1`. I looked
at using the private `rata die` functions but that would require
reimplementation of quite a lot of code - or making some private
functions public.
* Support years down to -4713 in date, timestamp and
timestampz type since that is the minimum year supported
by Postgresql
* Support years up to 9999 in timestampz (which is less
than that supported by [Postgresql](https://www.postgresql.org/docs/9.1/datatype-datetime.html))
but is the maximum supported by `Calendar.ISO`.
* Add tests for negative dates, timestamps and timestampz
> Support negative years for date, timestamp and timestampz types

- mix.exs
Since https://github.com/elixir-ecto/postgrex/pull/547, Postgrex requires elixir v11 or superior.
> Require elixir v11+

- lib/postgrex/protocol.ex
- test/custom_extensions_test.exs
This PR fixes https://github.com/elixir-ecto/postgrex/issues/550
The change to `recv_parse_describe` ensures that in case the Protocol & Query's `types` differ, the Query gets a new ref (to trigger an update to the Ecto cache) and gets the Protocol's `types` (both of these are done in `describe_result/4`).
Todo:
> Fix invalid type error after failover

- lib/postgrex/extensions/bit_string.ex
- lib/postgrex/extensions/box.ex
- lib/postgrex/extensions/line_segment.ex
- lib/postgrex/extensions/name.ex
- lib/postgrex/extensions/numeric.ex
- lib/postgrex/extensions/path.ex
- lib/postgrex/extensions/polygon.ex
- lib/postgrex/extensions/raw.ex
- lib/postgrex/extensions/uuid.ex
- lib/postgrex/type_module.ex
Addresses [#549](https://github.com/elixir-ecto/postgrex/issues/549) by marking code that creates improper lists as `generated: true`.
If it's preferable to explicitly opt-out of the specific Dialyzer warnings (using `@dialyzer`), that's an easy change.
> Mark code that uses improper lists as generated

- CHANGELOG.md
- lib/postgrex/binary_utils.ex
- lib/postgrex/extensions/xid8.ex
- lib/postgrex/utils.ex
- test/query_test.exs
Fixes #558 
This patch adds support for the `xid8` type introduced in PostgreSQL 13.
> [#558] Support xid8 type

- lib/postgrex/stream.ex
reraise/2 takes stacktrace as second argument,
reraise/3 accepts optional arguments for the exception
> Fix reraise usage in DBConnection.Query.encode/3 for Postgrex.Copy

- lib/postgrex/utils.ex
- test/utils_test.exs
My application could not start because of empty PGPORT env variable. That behaviour was completely unexpected, because I provided ecto with port in application settings. So env variable wasn't going to be used anyway, but prevented application from starting.
> Fix possible crash on getting default opts

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/login_test.exs
This commit adds an optional third element in the `endpoints` config to be able to specify extra_ssl_options such as `server_name_indication` when using more than one host in the `endpoints` key.
More details are in https://github.com/elixir-ecto/postgrex/issues/571
> Add extra_ssl_opts to endpoints config

- lib/postgrex/replication.ex
This will allow the user to specify the LSN number to start replication at. 
It can be useful when, for instance, the server crashes and the replication slot's current position wasn't persisted to disk. This will cause some messages to be sent that the client already received. This will allow the client to restart replication where it left off.
> allow specification of replication start lsn

- .tool-versions
- lib/postgrex/protocol.ex
- lib/postgrex/replication.ex
- test/replication_test.exs
Related to https://github.com/elixir-ecto/postgrex/issues/578.
This PR alters `Postgrex.Replication` so that the initialization function doesn't start the replication process, but instead delegates those actions to different functions that can be used after the connection starts. 
3 functions have been added: `create_slot/4`, `drop_slot/3` and `start_replication/3`.
After replication has started, no other commands can be given to the connection so that the messages don't jumble.
> replication functions

- lib/postgrex/protocol.ex
- lib/postgrex/replication.ex
- lib/postgrex/type_module.ex
- lib/postgrex/types.ex
- test/replication_test.exs
This PR does the following:
- adds the ability to decode the rows returned by the simple queries executed on a replication connection
- returns the results from the existing simple queries, such as `create_slot` and `drop_slot` 
- adds the new commands `show`, `identify_server`, `timeline_history` and returns their results
> Replication: return results from simple queries + add more simple queries

- lib/postgrex/replication.ex
- test/replication_test.exs
This PR introduces two functions to convert LSN between its integer representation and string representation. 
These can come in handy when trying to reconcile the LSN coming from the replication messages (integer) against the LSN needed to start replication/the values returned by simple queries such as `identify_system` (string). 
For instance, a user might want to persist the last WAL record they processed so they can restart where they left off if their app crashes. I'd also like to use these to improve replication restart on auto reconnect so that the already processed WAL messages aren't replayed. 
I didn't see any official conversion formulas in the PostgreSQL docs, so I looked at their source code and also the source code from Debezium to see how they both do it. What I found was …
> LSN conversion

- .tool-versions
- lib/postgrex/protocol.ex
- lib/postgrex/replication.ex
- test/replication_test.exs
This PR introduces 2 new functions: `copy_table/3` and `publication_tables/3`. 
It also introduces back pressure for the replication command because this was needed for `copy_table/3` and could be applied to `start_replication/3` for free.
**Motivation**
Would like to eventually expose the tools needed to simulate the `CREATE SUBSCRIPTION` command from Postgres. These 2 functions would be critical to providing the initial snapshot functionality from that command. 
The idea behind Postgres's initial snapshot functionality can be summarized by this excerpt from the `copy_table/3` doc:
```
... a single main replication process alongside secondary replication processes for each table. 
An individual secondary process can be used to copy the initial snapshot for a given table and
then stream …
```
> Replication: copy tables

- .tool-versions
- lib/postgrex/replication.ex
- test/replication_test.exs
This PR adds the ability to resume replication on temporary slots, provided the user passes the `plugin` option to `start_replication/3`. Also added some tests for reconnections.
> Replication: reconnect temp slots

- lib/postgrex/notifications.ex
- lib/postgrex/protocol.ex
- lib/postgrex/simple_connection.ex
- test/notification_test.exs
- test/simple_connection_test.exs
I am opening this to get discussion and feedback going.
The goal is to make `Postgrex.Notifications` flexible enough to handle running simple arbitrary queries, in addition to the listen/unlisten/notify work it does currently. To make that possible without exposing private APIs, `Notifications` accepts a callback module with a default implementation that maintains the current functionality, but is extensible enough for people to implement their own notification logic.
> Notification callback module

- lib/postgrex/protocol.ex
- lib/postgrex/replication_connection.ex
- lib/postgrex/simple_connection.ex
- test/notification_test.exs
- test/replication_connection_test.exs
- test/simple_connection_test.exs
Previously a query like `SELECT 1; SELECT 2;` would pass `%PostgrexResult{rows:[["1"], ["2"]]}` to the `handle_result` callback. Now it will send `[%PostgrexResult{rows:[["1"]]}, %PostgrexResult{rows:[["2"]]}]`.
This implementation reuses the `:query` return value and the `handle_result` callback. Another way to go is to make a new return value/callback for multiple result queries. The former is a bit more straightforward imo but the latter is more in line with MyXQL's semantics. 
Actually, now that I'm writing this, I'm thinking it's probably better to keep the semantics the same between the drivers, even if the implementation is completely different. But please let me know what you think. Thanks!
One more thing I realized: it will add some extra complexity to use MyXQL's semantics …
> separate multiple results in simple queries

- lib/postgrex/types.ex
When the [hexdocs are generated](https://hexdocs.pm/postgrex/Postgrex.Types.html#t:oid/0), the link to postgres oid documentation is bad (points [here](http://www.postgresql.org/docs/9.4/static/datatype-oid.html.) instead of [here](http://www.postgresql.org/docs/9.4/static/datatype-oid.html)). This just updates to markdown so the link doesn't include the period at the end of the sentence.
> docs:  fix typo in typedoc

- lib/postgrex/replication_connection.ex
- test/replication_connection_test.exs
When `:auto_reconnect` is set to true it isn't possible to resume the replication after a reconnect due to the process being in a streaming state. 
Any `{:query, ...}` or `{:stream, ...}` from in the `handle_connect` callback end up in the [`stream_in_progress`](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/replication_connection.ex#L552) and the warning `09:21:28.465 [warning] received query while stream is already in progress` is printed.
The actual replication is not resumed / restarted just the connection.
This PR just sets `:streaming` to `nil` on disconnect so that one can resume / recreate the replication slot in `handle_connect`.
Also a documentation fix for the correct plugin name 😄
> Fix! Replication streaming can be resumed after reconnect

- lib/postgrex/protocol.ex
- lib/postgrex/scram.ex
- lib/postgrex/scram/locked_cache.ex
Adds a final step in the SCRAM authentication to verify the server signature is correct.
Disclaimer: I'm for sure not an expert in this stuff. I just studied how libpq implemented it: https://github.com/postgres/postgres/blob/master/src/interfaces/libpq/fe-auth-scram.c.
> Add SCRAM server signature verification

- lib/postgrex/protocol.ex
While looking into an ultimately unrelated PG issue and perusing our PgBouncer logs we noticed that our Ecto connections are not being gracefully terminated. This manifested in spurious `client unexpected eof` disconnection messages, which could make a real scenario involving dropped connection trickier to diagnose were it ever to occur. So while this doesn't seem to impact the database in any material way, we figured it wouldn't hurt to follow the protocol if possible. This is what the [PostgreSQL protocol Message Flow section on Termination](https://www.postgresql.org/docs/current/protocol-flow.html#id-1.10.6.7.11) has to say:
> The normal, graceful termination procedure is that the frontend sends a Terminate message and immediately closes the connection
> In rare cases (such as an …
> Gracefully terminate connection when disconnecting

- lib/postgrex/protocol.ex
The connection disconnecting might be ssl.
> Respect socket type when terminating

- lib/postgrex/replication_connection.ex
to match `START_REPLICATION` `publication_names` ([line 84](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/replication_connection.ex#L84)).
This fixes the error
`message: "publication \"postgrex_example\" does not exist"`
otherwise experienced if `auto_reconnect: false`. If auto_reconnect is `true`, it will simply reconnect after error, but won't display any error messages, which is failing silently to anyone trying the example exs script.
You can observe `handle_disconnect` being called after _any_ time the connection gets wal content, which led to me experimenting with setting `auto_reconnect` to `false` in hopes an error message would surface (and it did).
> Fixes PUBLICATION name in docs 

- lib/postgrex/extensions/oid.ex
- test/query_test.exs
So that queries like this will work: `query("select $1::text::regconfig", ["english"])`
> Decode regconfig

- .github/workflows/ci.yml
- README.md
- lib/postgrex/builtins.ex
- lib/postgrex/extensions/multi_range.ex
- lib/postgrex/extensions/multirange.ex
- lib/postgrex/extensions/range.ex
- lib/postgrex/types.ex
- lib/postgrex/utils.ex
- test/query_test.exs
This PR adds support for the multirange data type. This was introduced into Postgres in version 14. Someone expressed interest in it here: https://groups.google.com/g/elixir-ecto/c/yVVBLLcLCD4.
A multirange looks like an array of ranges but it is different in a few ways. Postgres will remove overlaps if they exist, the binary protocol is different and the oid and sub oids are classified differently in the pg_type/pg_range catalogs
References:
- Postgres docs: https://www.postgresql.org/docs/14/rangetypes.html
- Binary protocol: https://github.com/postgres/postgres/blob/master/src/backend/utils/adt/multirangetypes.c#L328
> Add Multirange extension

- lib/postgrex/protocol.ex
Postgrex version of this MyXQL PR: https://github.com/elixir-ecto/myxql/pull/162
The issue: 
When `handle_{begin, commit, rollback}` have an error, `{:error, error, state}` is returned to DBConnection and doesn't cause the connection to leave its transaction.  Returning `{:error, state}` to DBConnection will cause `handle_begin`/`handle_commit` to disconnect and `handle_commit` to attempt a rollback.
Relevant parts from DBConnection:
- https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection.ex#L1684
- https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection.ex#L1703
- https://github.com/elixir-ecto/db_connection/blob/master/lib/db_connection.ex#L1734
> Return `{:error, state}` on transaction error

- lib/postgrex.ex
Based on [this comment](https://github.com/elixir-ecto/postgrex/issues/497#issuecomment-1404321658), it seems helpful to highlight this. 
It's a bit hidden in the Postgres docs,  you'd have to know where to find it in the protocol pages https://www.postgresql.org/docs/current/protocol-flow.html.
> Explain unnamed prepared statements in docs

- lib/postgrex/replication_connection.ex
- test/replication_connection_test.exs
Similar to https://github.com/elixir-ecto/postgrex/pull/643, but for the other connection. Once the other PR is merged, we can also remove the direct dependency to connection in the meantime.
> Use gen_statem in Postgrex.ReplicationConnection

- lib/postgrex/notifications.ex
- lib/postgrex/simple_connection.ex
- mix.exs
- test/notification_test.exs
- test/simple_connection_test.exs
First pass, but seems to be quite promising. 🙃
> Use gen_statem in Postgrex.SimpleConnection

- lib/postgrex/simple_connection.ex
Closes https://github.com/elixir-ecto/postgrex/issues/648.
> Fix timeout handling in Postgrex.SimpleConnection

- lib/postgrex/builtins.ex
- test/query_test.exs
Based on https://elixirforum.com/t/postgrex-range-behavior-is-confusing/56654
> Comment on how range retrieval works

- lib/postgrex/notifications.ex
To have the documentation render as intended.
> Fix markdown link syntax in notifications.ex

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- lib/postgrex/types.ex
- mix.lock
It is becoming more [common](https://github.com/elixir-ecto/postgrex/issues/645#issuecomment-1462931379) to use the "[postgres wire protocol](https://github.com/elixir-ecto/postgrex/issues?q=is%3Aissue+wire+protocol+is%3Aclosed)" for non-postgres projects. Many of these projects "support" the basic type bootstrap query, but do not support the [Array+subquery syntax nor custom types](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex/types.ex#L90). 
I added a configuration option to pass to the repo/start_link that enables this:
`skip_comp_oids: true|false` 
Appears to work in my test cases but its pretty difficult to write an actual test for this without mocking the connection? Any guidance would be helpful.
> Add configuration to skip querying of comp_oids

- lib/postgrex/result.ex
- test/query_test.exs
`Table.Reader` expects unique column names, since it uses the keys as row/columns map keys. We decided to suffix duplicate names with `_n`.
> Handle duplicate column names in Table.Reader implementation

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/transaction_test.exs
We're using this option at @knocklabs to inject comments for all transactions executed via the `Ecto.Repo.transaction/2` callback, which is gives us more granular insight into transaction performance in our RDS performance insights dashboard. We'd like to upstream it!
I wasn't sure where to add unit test coverage for this, if anywhere. Nor was I sure how I should try to sanitize the input, if at all.
More context in the ecto-elixir Google Group discussion here: https://groups.google.com/g/elixir-ecto/c/vUImb5ZX_CI
> feat: `commit_comment` option for prepending a SQL comment to a `COMMIT` statement

- lib/postgrex/protocol.ex
Sample message printed by DbConnection:
```
[error] Postgrex.Protocol (#PID<0.387.0>) failed to connect: ** (ArgumentError)
missing the :database key in options for repo TestEctoIssue.Repo
```
> Return ArgumentError when missing :database key in config

- lib/postgrex/replication_connection.ex
- test/replication_connection_test.exs
Currently the only way to stop the replication connection workflow is to raise / exit from within a callback.
This allows callback to return {:disconnect, reason} and either stop cleanly (if auto_reconnect:false) or restart the replication connection (if set to true)
> ReplicationConnection: allow callback to trigger disconnect

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/login_test.exs
@chrismccord, let me know if this works. For now, this means you need to explicitly set `ssl: :verify_full` in your config file but we can support "ssl=verify_full" via query string too.
> Streamline SSL experience

- lib/postgrex/extensions/time.ex
- lib/postgrex/extensions/timetz.ex
- test/calendar_test.exs
Continuation of the[ last PR](https://github.com/elixir-ecto/postgrex/pull/684), which only added it for timestamp.
I still have to add it for timestamptz but need a bit of time to figure out the functions to use.
> Use type modifier in time and timetz extensions

- lib/postgrex/type_module.ex
I thought this might be helpful for new people who might be intimidated by the macros. Also it will help me when I come back to this module in a few years and can't remember what it does.
> Add doc to define function in type module

- lib/postgrex/extensions/timestamptz.ex
- test/calendar_test.exs
I think we can just do this? Postgres will return an error if the timestamp is out of range with the message 
>message: "timestamp out of range:..."
> Remove max year from timestamptz

- lib/postgrex/extensions/timestamptz.ex
- test/calendar_test.exs
- test/query_test.exs
The old code was using `DateTime.from_unix` to decode the result for Postgres so I changed it to be like the timestamp extension and use `DateTime.from_gregorian_seconds`. This seems to be the best way to get arbitrary precision in the Elixir struct, from what I can see.
I also moved some of the timestamp tests to be in the calendar test module so that all the tests are in there.
> Honour precision with timestamptz extension

- lib/postgrex/replication_connection.ex
- test/replication_connection_test.exs
This change is in relation to Issue #692. It now allows a new stream to be created right after a COPY command. The test took a little bit of configuring to get the chain of events to fire off in the expected way. If there is a better way to handle this, any candid feedback is welcome.
Example Repl Module:
```elixir
defmodule MyApp.Repl do
use Postgrex.ReplicationConnection
def start_link(opts) do
extra_opts = [
auto_reconnect: true
]
Postgrex.ReplicationConnection.start_link(__MODULE__, :ok, extra_opts ++ opts)
end
@impl true
def init(:ok) do
{:ok, %{step: :disconnected, transaction: nil}}
end
@impl true
def handle_connect(state) do
query = "BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY"
{:query, query, %{state | step: :start_transaction}}
end
@impl true
def …
```
> REPLICATION: Allow starting one stream right after another

- lib/postgrex/types.ex
I'm not completely sure this is what you meant but I think `how Postgrex encodes and decodes data coming from Postgrex` seems to be a duplicate by mistake.
> Fix typo in docs for Types.define/3

- .github/workflows/ci.yml
- lib/postgrex/extensions/interval.ex
- test/query_test.exs
Addresses https://github.com/elixir-ecto/postgrex/issues/688 besides the deprecation of `Postgrex.Interval`.
The following changes were made:
- allow encoding of `Duration` structs for postgres interval extension
- allow decoding postgres interval types to `Duration` structs if the option `:interval_decode_type` is set to `Duration`
- both of the above two are only allowed if the elixir version is at least 1.17.0
Some notes:
- when breaking down the postgres response (microseconds, days and months) into the fields for the `Duration` struct, I went with the same style we use for `Postgrex.Interval`: translate the lower units into the higher units as much as possible
- the type modifier postgres returns for intervals is not an integer from 0 to 6. i will try to find out what it means but …
> Add support for Elixir Durations

- lib/postgrex/replication_connection.ex
- lib/postgrex/simple_connection.ex
When I was testing durations I kept seeing logs like this while running the tests
```elixir
07:40:52.702 [error] :gen_statem #PID<0.1557.0> terminating
** (stop) {:bad_return_from_init, {:stop, %Postgrex.Error{message: nil, postgres: %{code: :invalid_catalog_name, file: "postinit.c", line: "877", message: "database \"nobody_knows_it\" does not exist", pg_code: "3D000", routine: "InitPostgres", severity: "FATAL", unknown: "FATAL"}, connection_id: nil, query: nil}, %Postgrex.SimpleConnection{idle_interval: 5000, protocol: nil, auto_reconnect: false, reconnect_backoff: 500, state: {Postgrex.Notifications, %Postgrex.Notifications{from: nil, ref: nil, auto_reconnect: false, connected: false, listeners: %{}, listener_channels: %{}}}}}}
```
Checking the erlang docs it seems like `{:stop, …
> Fix `stop` return from gen_statem `init`

- README.md
- lib/postgrex/types.ex
Adds `Duration` to the docs. I also added the `:allow_infinite_timestamps` option to the documentation because I saw it was missing.
> Add `Duration` to docs.

- lib/postgrex/extensions/interval.ex
- lib/postgrex/extensions/time.ex
- lib/postgrex/extensions/timestamp.ex
- lib/postgrex/extensions/timestamptz.ex
- lib/postgrex/extensions/timetz.ex
- test/query_test.exs
In the previous PR we hardcoded the precision to 6 because we didn't know how to deal with the type modifier.
I got pointed in the right direction by the nice people at Postgres. The type modifier for intervals takes into account two different things:
1. The allowed fields (i.e. only `days`, `years`, `days to years` and stuff like that), represented as a 16-bit bit field
2. The precision represented as a 16 bit integer
The right most 16 bits in the type modifier are the precision. I was pointed to the right places in their code [here](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/backend/utils/adt/timestamp.c;h=69fe7860ede062fc8be42e7545b35e69c3e068c4;hb=HEAD#l1151) and [here](https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/include/utils/timestamp.h;h=a6 …
> Respect precision for intervals

- lib/postgrex/extensions/interval.ex
Closes https://github.com/elixir-ecto/postgrex/issues/700
I don't use dialyzer but I think this should do it. It's the same strategy we use for extensions like timestamp that also have a user defined option.
> Fix dialyzer warning for interval

- lib/postgrex/extensions/interval.ex
Really not sure about the latest warning
```elixir
deps/postgrex/lib/postgrex/type_module.ex:1084:call
The function call will not succeed.
:erlang.band(_mod :: nil, 65535)
will never return since the 1st arguments differ
from the success typing arguments:
(integer(), integer())
```
@oliver-kriska  could you try this branch before we merge? ty
> Fix dialyzer issues with interval extension, part 2

- lib/postgrex/extensions/array.ex
- lib/postgrex/extensions/multirange.ex
- lib/postgrex/extensions/range.ex
- test/calendar_test.exs
- test/query_test.exs
Closes https://github.com/elixir-ecto/postgrex/issues/704
The issue is with nested super types we may pass `{extension, modifier}` down so we end up with `{{extension, modifier}, nil}`. 
We want to flatten it out and pass `nil` for the range modifier because we don't know how the Postgres modifier for ranges works yet. Passing `nil` will have it default to what it was before we started handling modifiers.
> Fix nested super type modifier handling

- lib/postgrex.ex
The [typespec](https://github.com/elixir-ecto/postgrex/blob/master/lib/postgrex.ex#L249) for `Postgrex.start_link/1` is incorrect. This function wraps `DBConnection.start_link/2` which has a `GenServer.on_start()` [type](https://github.com/elixir-lang/elixir/blob/v1.14.1/lib/elixir/lib/gen_server.ex#L714C34-L714C84).
I'd like to introduce an accurate type for `Postgrex.start_link/1`.
> Fix start_link typespec

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/query_test.exs
Recently there was introduced commit_comment to prepend comment before the commit keyword
I wanted to propose something similar for all queries - It will be useful for prepending [sqlcommenter](https://github.com/QuerySorcery/sqlcommenter) comments to queries but any other info is possible. 
I tried different hacks to get around this limitation but this has to be implemented in postgrex just before the query is sent to the database.
I found the place where to add this code by trial and error, any suggestion welcome how to make it better.
Also is it possible to test it somehow? Currently I'm logging it in the database but it would be nice to log the data that is sent to the database. Maybe testing the encoder is enough?
```
2024-10-11 21:44:02.715 …
```
> allow to  append comment to query

- lib/postgrex.ex
- lib/postgrex/protocol.ex
This pr adds comments to prepare_execute function.
I also renamed the validation helper because it required negation everywhere.
> dk_fix_missing_comments

- lib/postgrex.ex
- lib/postgrex/type_module.ex
- test/query_test.exs
This can help if the user is passing a single value as a parameter or something like that. Otherwise the function clause error can be a bit cryptic.
> Raise a nice error message of params is not a list

- lib/postgrex.ex
This way we have a shorthand:
iex> Postgrex.query!(pid, "SELECT NOW()")
This also matches MyXQL API.
> Default params to []

- lib/postgrex/protocol.ex
Not actually sure if it's a typo, but I couldn't quickly [find](https://github.com/search?q=repo%3Aelixir-ecto%2Fpostgrex%20active_one&type=code) any other instances of `:active_one` in the codebase :)
> possible typo

- lib/postgrex/simple_connection.ex
postgrex 0.17.5
oban 2.18.3
we are using oban with postgres notifiers and in a few services we have a port leaks
_blue line is fix hotload_
the problem is that the ports are not closed on `{:connect, :reconnect}` handle, it just drops the `protocol` state and creates a new one
```elixir
08:09:21.320006 <0.3785.0> Postgrex.SimpleConnection.handle_event(:info, {:tcp, #Port<0.84514854>,
<<69, 0, 0, 0, 115, 83, 70, 65, 84, 65, 76, 0, 86, 70, 65, 84, 65, 76, 0, 67,
53, 55, 80, 48, 53, 0, 77, 116, 101, 114, 109, 105, 110, 97, 116, 105, 110,
103, 32, 99, 111, 110, 110, 101, 99, 116, 105, ...>>}, :no_state, %Postgrex.SimpleConnection{
idle_interval: 5000,
protocol: %Postgrex.Protocol{
sock: {:gen_tcp, #Port<0.84514854>},
connection_id: 3537365,
connection_key: 904133435,
peer: {{10, 129, 1, 100}, …
```
> call disconnect on protocol when reconnecting in simple connection

- lib/postgrex/extensions/multirange.ex
- lib/postgrex/simple_connection.ex
I noticed these minor doc issues while investigating a `SimpleConnection` bug.
> Minor link correction and moduledoc cleanup

- lib/postgrex.ex
- test/query_test.exs
I'm not sure if it makes sense to precompile binary pattern for that?
> check_for_null_in_comment

- lib/postgrex/replication_connection.ex
- lib/postgrex/simple_connection.ex
- When the ReplicationConnection encounters a socket error, it reconnects to another socket without properly closing the current one (similar to #717).
- When the ReplicationConnection fails to establish a connection, it doesn’t log any errors and simply retries indefinitely.
If Postgres terminates a replication connection process due to an OOM issue or a network error:
- Postgrex creates a new ReplicationConnection without closing the previous one.
- This repeats up to 10 times. (with auto_reconnect option)
- The max_wal_senders limit (default: 10) is reached, preventing new ReplicationConnection from being created.
- The system enters a silent infinite loop of reconnecting without any logs.
This issue has occurred in my production app during periods of network instability.
- Invoke …
> Call disconnect on protocol when reconnecting in Replication connection 

- README.md
- lib/postgrex/extensions/interval.ex
- test/query_test.exs
> Have Duration return same units as Postgrex.Interval

- lib/postgrex.ex
- lib/postgrex/protocol.ex
A while ago we added a `search_path` option to start_link. But looking closer I saw it was already supported by the `parameters` option. 
I think we have to continue letting people use `search_path` so their apps don't break. But internally I'm changing it to re-use `parameters` so that we don't send an extra query unnecessarily on startup.
> Search path is already supported by parameters option

- .github/workflows/ci.yml
- lib/postgrex/extensions/ltxtquery.ex
- lib/postgrex/utils.ex
- test/query_test.exs
https://www.postgresql.org/docs/current/ltree.html
https://github.com/postgres/postgres/blob/master/contrib/ltree/ltxtquery_io.c#L428
https://github.com/postgres/postgres/blob/master/contrib/ltree/ltxtquery_io.c#L603
> Add ltxtquery support

- lib/postgrex/protocol.ex
Otherwise SSL fails, for example:
```
iex(1)> :ssl.connect ~c"google.com", 443, [verify: :verify_peer]
{:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}
```
> Use cacerts on verify peer

- lib/postgrex/utils.ex
- test/utils/envs_test.exs
Hello! First of all, thank you for this amazing library
This PR addresses a bug where setting the `PGHOST` environment variable can unintentionally override explicitly passed connection options like `:hostname`, `:socket_dir`, `:socket`, or `:endpoints`.
- Fix: Updated `default_opts/1` to derive the host from `PGHOST` **only if** no endpoint-related options are explicitly provided (`:socket`, `:socket_dir`, `:hostname`, or `:endpoints`).
- Test: Added test coverage to ensure that explicitly provided connection options correctly take precedence over environment-derived defaults.
- Important note: This might cause breaking changes to existing users if they might be inadvertently overriding values that are currently ignored.
When `PGHOST` is set (e.g., to a Unix socket path), Postgrex …
> Prioritize explicit endpoint options over PGHOST-derived defaults
