elixir-ecto/postgrex

- test/query_test.exs
Test for situation in https://github.com/ericmj/postgrex/issues/44
> Add test for date value of -1 (1999-12-31)

- lib/postgrex/extensions/binary.ex
- test/query_test.exs
Previously the encoded integer (ranges) would be decoded by Postgres as wrapped around.
> Enforce bounds of integers and integer ranges.

- lib/postgrex/errcodes.txt
- lib/postgrex/error.ex
- lib/postgrex/error_code.ex
- lib/postgrex/protocol.ex
- test/error_code_test.exs
- test/query_test.exs
> Translate Postgres error codes into atoms.

- lib/postgrex/errcodes.txt
- test/error_code_test.exs
Hopefully that will last a while :)
> Update errcodes.txt now that 9.5 is getting new error codes.

- lib/postgrex/connection.ex
For more information: https://groups.google.com/forum/#!topic/elixir-ecto/Xav1cohJ-Mw
> Set internal socket buffer based on sndbuf/recbuf

- lib/postgrex/connection.ex
- lib/postgrex/messages.ex
- lib/postgrex/protocol.ex
- lib/postgrex/utils.ex
- mix.exs
- mix.lock
Resolves #85. I haven't added reconnection/backoff as that might effect listen/unlisten and the type sever lock.
> Use Connection for Postgrex.Connection

- lib/postgrex/builtins.ex
- lib/postgrex/extensions/binary.ex
- test/query_test.exs
http://www.postgresql.org/docs/9.0/static/datatype-net-types.html
> Add support for Postgres' inet, cidr, and macaddr types

- lib/postgrex/connection.ex
- lib/postgrex/error.ex
- lib/postgrex/protocol.ex
- test/login_test.exs
Closes https://github.com/ericmj/postgrex/issues/94
I only added one test to check for the formatted error. Is this alright? Also, some tests fail for me. 
Do they fail for you too?
> Format all TCP errors

- lib/postgrex/connection.ex
- lib/postgrex/protocol.ex
- test/query_test.exs
- test/test_helper.exs
Closes https://github.com/ericmj/postgrex/issues/101
Here's the PR for async queries. Thanks a lot for the help, @fishcakez!
> Async query

- lib/postgrex/protocol.ex
- lib/postgrex/result.ex
- lib/postgrex/types.ex
Changes the decoders in the Result struct to a list of anonymous funs. This reduces the ets lookups by 1 per column by fetching format and decoder together. A similar change is done to reduce ets lookups by 1 per parameter when encoding.
It is possible that this decoder can bring gains to Ecto as it would be able to parse the rows in 1 pass.
Based on #108.
> Change Result decoders to a list of anon funs

- mix.exs
> Add Connection and Decimal to applications in mix.exs for exrm.

- lib/postgrex/notifications.ex
- lib/postgrex/protocol.ex
> Use simple query to listen/unlisten

- lib/postgrex/protocol.ex
The first commit moves the enum based implementation into binary decoding. The new implementation assumes that once an integer is found in the tag, only integers will be expected. I.e. we can have "INSERT 0 1" and "SELECT 1" and "ROLLBACK" but never "COMMAND 0 ANOTHER 1". @ericmj is this assumption correct?
The second commit inlines common commands: insert, select, update, delete, begin, rollback and commit.
> Optimize tag decoding

- lib/postgrex/protocol.ex
- test/query_test.exs
This change means the connection prepared query cache is now in sync with the backend and error handling (of duplicate prepared queries) relies on the backend's error (along with other errors). There is a special case where we must delete unnamed queries if an error occurs.
Closes #150.
> Only describe queries that are already prepared

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- test/null_mapping_test.exs
@fishcakez 
this still needs to be documented and the opt name is probably not ideal but making this pr for discussion on whether this approach is acceptable
> allow custom encoding/decoding of postgres' NULL on a per query basis

- lib/postgrex.ex
Adds supervisor child specification to public api.
> Add child_spec/1 to public api

- README.md
- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/query_test.exs
- test/transaction_test.exs
> Support PgBouncer transaction/statement pooling

- README.md
Just to make it clear it works.
> Add pg 9.5 to README

- lib/postgrex/protocol.ex
- lib/postgrex/types.ex
I think we could spare the memory to give a better error here, thoughts?
> Improve no extension errors

- lib/postgrex/protocol.ex
- lib/postgrex/type_server.ex
- test/type_server_test.exs
Closes #194.
Once bootstrapped use links instead of monitors. Links mean we can still track processes who are not connected but will reconnect soon. This means we won't reap if database temporarily disappears or `pool_size: 0, pool_overflow: n` is used with `DBConnection.Sojourn` pool.
/cc @josevalim
> Link to bootstrapped connections and delay reaping

- lib/postgrex/protocol.ex
- lib/postgrex/query.ex
- lib/postgrex/types.ex
- test/query_test.exs
- test/test_helper.exs
*WORK IN PROGRESS*
@josevalim is this a suitable approach to handle new oids?
> Rebootstrap on every connect

- lib/postgrex.ex
- lib/postgrex/error.ex
- lib/postgrex/protocol.ex
- test/client_test.exs
- test/login_test.exs
> Raise DBConnection.ConnectionError on connection error

- lib/postgrex/protocol.ex
- test/login_test.exs
@MartinElvar hopefully this will help prevent issues like yours.
> Improve connect error message

- lib/postgrex/extensions/numeric.ex
- mix.lock
> Optimize numeric encoding/decoding

- lib/postgrex/protocol.ex
- test/query_test.exs
@jwarlander could you try this branch?
> Handle ping errors

- lib/postgrex.ex
- test/postgrex_test.exs
> Raise error when :ssl application is required and not started

- lib/postgrex/extensions/numeric.ex
- test/query_test.exs
Fixes https://github.com/elixir-ecto/postgrex/issues/329
> rise ArgumentError when encoding infinite Decimal

- CHANGELOG.md
- mix.exs
- mix.lock
Update the v0.13 branch with the latest release
> Update v0.13 branch with latest release (v0.13.3)

- lib/postgrex/extensions/path.ex
- test/query_test.exs
> Fix path open/closed byte parity

- lib/postgrex/protocol.ex
Closes #363
@fishcakez I'm not really sure how to test this. Any tips?
> Handle errors in response to SSLRequest

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/login_test.exs
Fixes [365](#365), let me know if any changes are needed.
> Add :socket_file option.

- test/utils_test.exs
Test for this change: https://github.com/elixir-ecto/postgrex/pull/369
> Add test for Utils.parse_version/1

- lib/postgrex/builtins.ex
- lib/postgrex/extensions/range.ex
- test/query_test.exs
- test/type_module_test.exs
> Explicitly encode and decode ranges as empty or unbound

- lib/postgrex/notifications.ex
This is a first attempt at addressing #386 
@josevalim mentioned that this is already implemented for normal postgrex connections and it looks to me like this is [handled as part of the DbConnection library](https://github.com/elixir-ecto/db_connection/blob/7588c321be4be4e740c7121dd1885569468228e9/lib/db_connection/connection.ex#L371-L379). So I tried to follow the same pattern here and use the [GenServer timeout feature](https://hexdocs.pm/elixir/1.6.5/GenServer.html#c:handle_call/3) to make sure that if our connection is sitting idle for too long we send a ping to the server.
In this case I've just matched on `{:ok, updated_protocol}` because if the ping fails it means something has gone wrong with our connection and I had no idea how to recover from that, so it seemed best to just …
> implement an idle_timeout for Postgrex.Notification to ping the connection

- .travis.yml
- README.md
- lib/postgrex/messages.ex
- lib/postgrex/protocol.ex
- mix.exs
- mix.lock
- test/login_test.exs
- test/test_helper.exs
Support scram-sha-256 authentication method new in PostgreSQL 10.
> Support scram-sha-256 authentication #374

- lib/postgrex/extensions/timestamp.ex
- test/calendar_test.exs
Fixes #417
My code editor runs the formatter on save which has produced a few extra changes in the file, I can try to remove that if desired.
> Encode %DateTime{} for timestamp columns

- lib/postgrex/protocol.ex
> {:disconnect, _, _, _} to {:disconnect, _, _}

- lib/postgrex.ex
Ref https://github.com/elixir-ecto/postgrex/pull/414#issuecomment-440727642
cc @fishcakez
> Update :disconnect_on_error_codes docs

- lib/postgrex.ex
> Update close!/3 to match spec and close/3

- lib/postgrex/utils.ex
- test/utils_test.exs
The implementation considers `"alpha" < "beta" < 0`. To achieve this, we convert the value to charlist, take the head and make it negative :)
> Fixes #464.

- lib/postgrex/scram.ex
Wrap the call to :crypto.hmac/3, which is being removed in OTP-24.
> Support OTP-24

- lib/postgrex.ex
Clears up the confusion which lead to #551
> add information about client certificate authentication

- test/query_test.exs
> Run formatter to fix CI failure.

- lib/postgrex/protocol.ex
- lib/postgrex/replication.ex
- test/replication_test.exs
/cc @greg-rychlewski 
I am thinking of doing similar to copy/replication, and rather the command that starts it come from the process.
> Bring the ability of running custom queries to Postgrex.Replication

- lib/postgrex/result.ex
- mix.exs
- mix.lock
- test/query_test.exs
> Implement the Table.Reader protocol for query result

- lib/postgrex/utils.ex
- test/utils/envs_test.exs
> Support Unix sockets in `:hostname` and `PGHOST`

- lib/postgrex/extensions/numeric.ex
- test/query_test.exs
- test/test_helper.exs
- test/transaction_test.exs
> Support infinity value on numerics/decimals (postgres 14+) 

- lib/postgrex.ex
Config files do not allowing passing functions, so the docs give an example on how to use the `init` callback of the Ecto supervisor.
Based on recommendation given in #608
> Update docs for configuring :ssl_opts (#608)

- test/query_test.exs
- test/test_helper.exs
This reverts commit 5318aaea19500f323eb5b68f31ae5e89a748d474. I accidentally pushed to this repo instead of my fork.
> Revert "more tests"

- lib/postgrex/result.ex
- test/query_test.exs
> Add count to table reader metadata

- lib/postgrex.ex
- lib/postgrex/protocol.ex
- test/postgrex_test.exs
- test/query_test.exs
Closes https://github.com/elixir-ecto/postgrex/issues/619
> Add `:search_path` option to connection

- lib/postgrex/notifications.ex
Also, indicate effect on auto-reconnect and how to avoid the issue
Fixes https://github.com/elixir-ecto/postgrex/issues/637
> Mention inherent LISTEN race condition

- lib/postgrex/notifications.ex
Not sure what happened here but since the last 2 commits the formatter is complaining about this.
> Fix formatting

- lib/postgrex/extensions/lquery.ex
- lib/postgrex/extensions/ltree.ex
Closes https://github.com/elixir-ecto/postgrex/issues/651
I noticed a similar issue was solve here by using `generated: true`: https://github.com/elixir-ecto/postgrex/pull/556/files
Also I added some `location: :keep` that I missed in my original PR.
> Suppress improper list warnings

- lib/postgrex.ex
Fix for the outlined issue [here](https://github.com/elixir-ecto/postgrex/issues/656)
> fix: SSL configuration docs for failover case

- lib/postgrex/protocol.ex
Continuation of the DBConnection PR https://github.com/elixir-ecto/db_connection/pull/300
> Trap exits from `connect` callback

- lib/postgrex/extensions/box.ex
- lib/postgrex/extensions/circle.ex
- lib/postgrex/extensions/line_segment.ex
- lib/postgrex/result.ex
>  Fix module name in raise

- lib/postgrex.ex
I had the same question as the person in this issue: https://github.com/elixir-ecto/postgrex/issues/311
I didn't find an example in the docs, so I thought I'd add one.
> Add example with ANY()
